basePath: /
definitions:
  github_com_popvaleks_url-shortener_internal_lib_api_response.Response:
    properties:
      error:
        type: string
      status:
        type: string
    type: object
  internal_http-server_handlers_url_save.Request:
    description: Request to create a short URL
    properties:
      alias:
        type: string
      url:
        type: string
    required:
    - url
    type: object
  internal_http-server_handlers_url_save.Response:
    description: Response with the created alias
    properties:
      alias:
        type: string
      error:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Shortener service
  title: Url shortener
  version: "1.0"
paths:
  /url:
    post:
      consumes:
      - application/json
      description: Creates a short alias for the provided URL
      parameters:
      - description: URL shortening request data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_http-server_handlers_url_save.Request'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_http-server_handlers_url_save.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_popvaleks_url-shortener_internal_lib_api_response.Response'
      summary: Save URL
      tags:
      - url
swagger: "2.0"
